"""
Dataset validation + exploratory analysis for ProSafe ML V2.

1. Validates every ML-ready file (rows, columns, workers, timestamps, nulls,
   duplicates, class distribution, unique risk_level values, raw-baseline and
   forbidden columns). STOPS if any label other than Safe/Warning/Critical
   appears -- UNCERTAIN belongs to the data-quality gate, not the classifier.
2. Infers data-quality coverage (UNCERTAIN observations dropped offline).
3. Plots -- DEVELOPMENT workers only. W_002 contributes structure counts only.

Run from the project root:
    python src/eda.py
"""

from __future__ import annotations

import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import plot_style as ps
from utils import (
    CORE_FEATURE_COLUMNS,
    DEV_WORKERS,
    EDA_OUTPUTS_DIR,
    EXPOSURE_COLUMNS,
    EXTENDED_FEATURE_COLUMNS,
    RISK_CLASSES,
    SYNTHETIC_DATA_PATH,
    TARGET_COLUMN,
    W001_DATA_PATH,
    WORKER_COLUMN,
    _read_ml_ready,
    dataset_inventory,
    ensure_dirs,
    external_test_structure_inventory,
    session_coverage,
)


def _md_inventory(inv: dict) -> list[str]:
    lines = [f"### {inv['dataset']}", "",
             f"- rows: **{inv['rows']:,}**, columns: **{inv['columns']}**",
             f"- workers: {', '.join(f'{w} ({n:,})' for w, n in inv['workers'].items())}",
             f"- timestamps: {inv['timestamp_first']} -> {inv['timestamp_last']} "
             f"({inv['distinct_minute_timestamps']} distinct minute stamps; {inv['timestamp_resolution']})",
             f"- null cells: {inv['null_cells_total']:,} -> {inv['null_cells_by_column'] or 'none'}",
             f"- duplicate rows: {inv['duplicate_rows']}; duplicate (worker_id, timestamp) pairs: "
             f"{inv['duplicate_worker_timestamp_pairs']:,} (expected: ~60 rows share each minute stamp)",
             f"- **unique risk_level: {inv['risk_level_unique']}**",
             f"- class distribution: " + ", ".join(f"{c} {n:,} ({n / inv['rows']:.1%})" for c, n in inv['class_distribution'].items()),
             f"- raw baseline columns present: {inv['raw_baseline_columns_present'] or 'none (baseline_hr / baseline_body_temperature removed - verified)'}",
             f"- forbidden/audit columns present: {inv['forbidden_columns_present'] or 'none'}",
             ""]
    return lines


def validate_and_report(dev: pd.DataFrame) -> dict:
    inventories = [
        dataset_inventory(dev[dev["_source_file"] == SYNTHETIC_DATA_PATH.name], SYNTHETIC_DATA_PATH.name),
        dataset_inventory(dev[dev["_source_file"] == W001_DATA_PATH.name], W001_DATA_PATH.name),
    ]
    w002_inv, w002_cov = external_test_structure_inventory()
    inventories.append(w002_inv)
    coverage = session_coverage(dev) + w002_cov

    for inv in inventories:
        print(f"{inv['dataset']}: rows={inv['rows']:,} cols={inv['columns']} workers={list(inv['workers'])} "
              f"risk_level unique={inv['risk_level_unique']} nulls={inv['null_cells_total']} "
              f"dups={inv['duplicate_rows']} baselines={inv['raw_baseline_columns_present']}")

    cov = pd.DataFrame(coverage)
    cov.to_csv(EDA_OUTPUTS_DIR / "data_quality_coverage_inferred.csv", index=False)
    tot = cov.groupby("worker_id")[["expected_observations_1hz", "ml_ready_observations_valid_or_imputed",
                                    "uncertain_observations_inferred"]].sum()
    tot["uncertain_pct"] = (100 * tot["uncertain_observations_inferred"] / tot["expected_observations_1hz"]).round(2)

    per_worker = dev.groupby(WORKER_COLUMN)[TARGET_COLUMN].value_counts().unstack().reindex(columns=RISK_CLASSES).fillna(0).astype(int)
    lines = ["# Dataset validation (ProSafe ML V2)", "",
             "Generated by `src/eda.py`. W_002 is reported as **structure only** (counts, nulls, labels) - no feature "
             "values or distributions of the external test worker were examined before the model was frozen.", "",
             "## Label check", "",
             "Every file contains only `Safe`, `Warning`, `Critical`. **No `Uncertain` labels were found**, so the "
             "classifier is trained as a 3-class model; UNCERTAIN remains a data-quality outcome of the preprocessing gate.", "",
             "## Baseline columns", "",
             "`baseline_hr` and `baseline_body_temperature` are **absent** from all three files (verified). They are also on "
             "the forbidden-predictor list, so they could never enter `FEATURE_COLUMNS` even if re-added. Personalization "
             "is carried by `hr_deviation_bpm`, `hr_deviation_pct`, `body_temp_deviation_c`, `body_temp_deviation_pct`.", "",
             "## Datasets", ""]
    for inv in inventories:
        lines += _md_inventory(inv)
    lines += ["## Class distribution per development worker", "", per_worker.to_markdown(), "",
              "## Data-quality coverage (INFERRED - no audit file available)", "",
              "The ML-ready files exclude UNCERTAIN rows. The stream is 1 Hz, so every missing second inside a session is an "
              "observation the offline quality gate dropped. Session starts are inferred (see `utils.session_coverage`).", "",
              tot.to_markdown(), "", "Per session:", "", cov.to_markdown(index=False), ""]
    (EDA_OUTPUTS_DIR / "dataset_validation.md").write_text("\n".join(lines), encoding="utf-8")
    (EDA_OUTPUTS_DIR / "dataset_validation.json").write_text(json.dumps(
        {"inventories": inventories, "coverage_inferred": coverage}, indent=2, default=str), encoding="utf-8")
    return {"inventories": inventories, "coverage": cov}


def plot_class_distribution(dev: pd.DataFrame) -> None:
    pw = dev.groupby(WORKER_COLUMN)[TARGET_COLUMN].value_counts(normalize=True).unstack().reindex(
        index=DEV_WORKERS, columns=RISK_CLASSES).fillna(0)
    fig, ax = plt.subplots(figsize=(9, 3.8))
    y = np.arange(len(pw))[::-1]
    left = np.zeros(len(pw))
    for c in RISK_CLASSES:
        ax.barh(y, pw[c], left=left, height=0.55, color=ps.STATUS[c], label=c, edgecolor=ps.SURFACE, linewidth=2, zorder=3)
        for yi, l, v in zip(y, left, pw[c]):
            if v >= 0.06:
                ax.text(l + v / 2, yi, f"{v:.0%}", ha="center", va="center", fontsize=9,
                        color="white" if c != "Warning" else ps.INK, zorder=4)
        left += pw[c].values
    ax.set_yticks(y)
    ax.set_yticklabels([f"{w}  (n={int((dev[WORKER_COLUMN] == w).sum()):,})" for w in pw.index])
    ax.set_xlim(0, 1)
    ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.0%}"))
    ax.grid(axis="y", visible=False)
    ax.legend(ncol=3, loc="lower center", bbox_to_anchor=(0.5, -0.32))
    ax.set_title("Risk-level mix per development worker")
    ps.subtitle(ax, "Synthetic workers are Warning-heavy; real W_001 has the most Critical time")
    ps.save(fig, EDA_OUTPUTS_DIR / "01_class_distribution_by_worker.png")


def plot_feature_by_class(dev: pd.DataFrame) -> None:
    feats = ["hr_deviation_pct", "heart_rate_rolling_mean_30s", "body_temp_deviation_c", "ambient_temp_rolling_mean_300s",
             "uv_rolling_mean_300s", "gas_ratio_to_baseline", "noise_rolling_mean_60s", "noise_dose_pct", "hr_trend_60s_bpm_per_min"]
    fig, axes = plt.subplots(3, 3, figsize=(13, 10))
    for ax, f in zip(axes.ravel(), feats):
        data = [dev.loc[dev[TARGET_COLUMN] == c, f].dropna().values for c in RISK_CLASSES]
        bp = ax.boxplot(data, vert=True, widths=0.5, patch_artist=True, showfliers=False,
                        medianprops={"color": ps.INK, "linewidth": 1.5}, whiskerprops={"color": ps.AXIS},
                        capprops={"color": ps.AXIS})
        for patch, c in zip(bp["boxes"], RISK_CLASSES):
            patch.set_facecolor(ps.STATUS[c])
            patch.set_alpha(0.75)
            patch.set_edgecolor(ps.SURFACE)
        ax.set_xticks([1, 2, 3])
        ax.set_xticklabels(RISK_CLASSES)
        ax.set_title(f, fontsize=10.5)
        ax.grid(axis="x", visible=False)
    fig.suptitle("Key features by risk level (development workers; whiskers 1.5 IQR, outliers hidden)",
                 x=0.01, ha="left", fontsize=13, fontweight="semibold", color=ps.INK)
    ps.save(fig, EDA_OUTPUTS_DIR / "02_features_by_risk_level.png")


def plot_correlation(dev: pd.DataFrame) -> None:
    corr = dev[CORE_FEATURE_COLUMNS].corr()
    from matplotlib.colors import LinearSegmentedColormap
    cmap = LinearSegmentedColormap.from_list("div", ["#d03b3b", "#f0efec", "#2a78d6"])
    fig, ax = plt.subplots(figsize=(12, 10))
    im = ax.imshow(corr.values, cmap=cmap, vmin=-1, vmax=1)
    ax.set_xticks(range(len(corr)))
    ax.set_yticks(range(len(corr)))
    ax.set_xticklabels(corr.columns, rotation=90, fontsize=8)
    ax.set_yticklabels(corr.columns, fontsize=8)
    ax.grid(False)
    fig.colorbar(im, ax=ax, fraction=0.035, label="Pearson r")
    ax.set_title("CORE feature correlation (development workers)")
    ps.save(fig, EDA_OUTPUTS_DIR / "03_core_correlation.png")


def plot_missingness(dev: pd.DataFrame) -> None:
    miss = dev[EXTENDED_FEATURE_COLUMNS].isna().mean().sort_values()
    miss = miss[miss > 0]
    fig, ax = plt.subplots(figsize=(9, 0.45 * len(miss) + 1.2))
    ps.single_hbar(ax, list(miss.index[::-1]), list(miss.values[::-1] * 100), xlim=(0, max(miss.values) * 100 * 1.25), fmt="{:.2f}%")
    ax.set_xlabel("% of development rows that are NaN")
    ax.set_title("Where the ML-ready data contains NaN")
    ps.subtitle(ax, "Long-window features are NaN during session warm-up; a few raw sensor values are missing")
    ps.save(fig, EDA_OUTPUTS_DIR / "04_missingness.png")


def plot_timelines(dev: pd.DataFrame) -> None:
    fig, axes = plt.subplots(len(DEV_WORKERS), 1, figsize=(13, 1.3 * len(DEV_WORKERS) + 0.8), sharex=False)
    code = {c: i for i, c in enumerate(RISK_CLASSES)}
    for ax, w in zip(axes, DEV_WORKERS):
        g = dev[dev[WORKER_COLUMN] == w]
        x = np.arange(len(g))
        for c in RISK_CLASSES:
            m = (g[TARGET_COLUMN] == c).values
            ax.scatter(x[m], np.full(m.sum(), code[c]), s=2, color=ps.STATUS[c], marker="|", linewidths=0.6)
        ax.set_yticks(range(3))
        ax.set_yticklabels(RISK_CLASSES, fontsize=8)
        ax.set_ylim(-0.6, 2.6)
        ax.set_ylabel(w, rotation=0, ha="right", va="center", fontsize=9, color=ps.INK)
        ax.grid(axis="y", visible=False)
        ax.tick_params(axis="x", labelsize=8)
    axes[-1].set_xlabel("ML-ready row (1 Hz order within worker)")
    axes[0].set_title("Risk-level timeline per development worker")
    ps.save(fig, EDA_OUTPUTS_DIR / "05_risk_timelines.png")


def summary_statistics(dev: pd.DataFrame) -> None:
    stats = dev[EXTENDED_FEATURE_COLUMNS].describe().T
    stats.to_csv(EDA_OUTPUTS_DIR / "summary_statistics_development.csv")
    by_class = dev.groupby(TARGET_COLUMN)[CORE_FEATURE_COLUMNS + EXPOSURE_COLUMNS].median().T[RISK_CLASSES]
    by_class.to_csv(EDA_OUTPUTS_DIR / "median_by_class_development.csv")


def main() -> None:
    ensure_dirs()
    ps.apply()
    dev = pd.concat([_read_ml_ready(SYNTHETIC_DATA_PATH), _read_ml_ready(W001_DATA_PATH)], ignore_index=True)
    validate_and_report(dev)
    summary_statistics(dev)
    plot_class_distribution(dev)
    plot_feature_by_class(dev)
    plot_correlation(dev)
    plot_missingness(dev)
    plot_timelines(dev)
    print(f"EDA written to {EDA_OUTPUTS_DIR}")


if __name__ == "__main__":
    main()
